# matrix of experiments to run - machine types and sizes are required

# This can obviously be expanded to more sizes or machines,
matrix:
  size: [2, 4, 6, 8]
  machine: ["n1-standard-1"]

# Flux Mini Cluster experiment attributes
minicluster:
  name: lammps
  namespace: flux-operator

# Each job can have a command and working directory
jobs:
  lmp:
    command: lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite
