apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: scaling-study-efa
  region: us-east-2
  version: "1.23"
        
availabilityZones: ["us-east-2b", "us-east-2c"]
managedNodeGroups:
  - name: launcher
    availabilityZones: ["us-east-2b"]
    instanceType: hpc6a.48xlarge
    minSize: 1
    maxSize: 1
    efaEnabled: true
    placement:
      groupName: eks-efa-testing
    taints:
      - key: "launcher"
        value: "true"
        effect: NoSchedule
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_eks.pub
  - name: workers
    availabilityZones: ["us-east-2b"]
    instanceType: hpc6a.48xlarge
    minSize: 64
    maxSize: 64
    efaEnabled: true
    placement:
      groupName: eks-efa-testing
    labels: { "flux-operator": "true" }
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_eks.pub
