# matrix of experiments to run - machine types and sizes are required
matrix:

  # Size of the MiniCluster - we are allowed to specify one size (and different pods)
  size: [4] # [64]

  # See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html#efa-instance-types
  # not all support efa
  machine: ["hpc6a.48xlarge"]

kubernetes:
  version: "1.23"

# Flux Mini Cluster experiment attributes
minicluster:
  name: lammps
  namespace: flux-operator
  
  # These are the sizes of MiniCluster we will iterate over
  size: [4] #[64, 32, 16, 8, 4]

variables:
  availability_zones: [us-east-2b, us-east-2c]
  region: us-east-2
  efa_enabled: true
  placement_group: eks-efa-testing

jobs:
  # I changed this to lmp-4-submit when I ran flux-cloud submit
  lmp-4-submit:
    command: lmp -v x 64 -v y 16 -v z 16 -in in.reaxc.hns -nocite
    # command: lmp -v x 64 -v y 16 -v z 8 -in in.reaxc.hns -nocite
    image: ghcr.io/rse-ops/lammps-efa:ubuntu-20.04
    repeats: 10
    memory: 340G
    # 4*94
    tasks: 376
    cpu: 94
    cores: 96

    # This indicates only run on the MiniCluster size 4
    size: 4

    # These are for flux submit
    limits:
      vpc.amazonaws.com/efa: 1
      memory: 340G
      cpu: 94

    requests:
      vpc.amazonaws.com/efa: 1
      memory: 340G
      cpu: 94
