# matrix of experiments to run - machine types and sizes are required

# These are mini runs intended for testing
matrix:
  size: [4]

  # See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html#efa-instance-types
  # not all support efa
  machine: ["hpc6a.48xlarge"]


# Flux Mini Cluster experiment attributes
minicluster:
  name: lammps
  namespace: flux-operator
  size: [2, 4]

variables:
  efa_enabled: true

# Each job can have a command and working directory
jobs:
  lmp-4-4-2:
     command: lmp -v x 4 -v y 4 -v z 2 -in in.reaxc.hns -nocite
  lmp-4-4-4:
     command: lmp -v x 4 -v y 4 -v z 4 -in in.reaxc.hns -nocite
  lmp-tasks-384:
     command: lmp -v x 64 -v y 8 -v z 4 -in in.reaxc.hns -nocite
  lmp-chonker:
    command: lmp -v x 64 -v y 16 -v z 8 -in in.reaxc.hns -nocite