apiVersion: batch/v1
kind: Job
metadata:
  name: indexed-job
spec:
  completions: [[size]]
  parallelism: [[size]]
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: worker
        image: docker.io/library/busybox
        command: [sleep, infinity]
