apiVersion: flux-framework.org/v1alpha1
kind: MetricSet
metadata:
  labels:
    app.kubernetes.io/name: metricset
    app.kubernetes.io/instance: metricset-sample
  name: metricset-sample
spec:
  pods: 4
  metrics:
   - name: network-chatterbug

     # mpirun --hostfile ./hostfile.txt --allow-run-as-root -N 16 /root/chatterbug/stencil3d/stencil3d.x 4 2 2 10 10 10 4 1
     # Custom options for chatterbug
     options:
       # Given specific arguments, only one command is supported
       command: stencil3d
       # Args to stencil3d
       args: "1 2 2 10 10 10 4 1"
       # mpirun arguments. 4 processes per node x 4 nodes, 16
       mpirun: "-N 16"
