apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:

  # Number of pods to create for MiniCluster
  size: 4
  tasks: 4

  # This starts the flux broker without a command (interactive)
  logging:
    quiet: false
    strict: false
    zeromq: true

  flux:
    wrap: "strace,-e,network,-tt"

  # This is a list because a pod can support multiple containers
  containers:
    - image: ghcr.io/rse-ops/nslookup:flux-sched-focal
      pullAlways: true
      command: sleep 10

      # Resource limits to ensure 1 pod assigned per node
      resources:
        limits:
          cpu: "1"

        requests:
          cpu: "1"
