apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "default-flavor"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue"
spec:
  namespaceSelector: {}
  resourceGroups: {}
  resourceGroups:
  - coveredResources: ["pods", "cpu"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "pods"
        nominalQuota: 1000
      - name: "cpu"
        # 8 nodes * 4 each
        nominalQuota: 40
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "user-queue"
spec:
  clusterQueue: "cluster-queue"
