apiVersion: v1
kind: Service
metadata:
  name: {{ service_name }}
spec:
  clusterIP: None
  selector:
    job-name: {{ name }}
---
apiVersion: batch/v1
kind: Job
metadata:
  # name will be derived based on iteration
  name: {{ name }}
spec:
  completions: {{ size }}
  parallelism: {{ size }}
  completionMode: Indexed
  {% if scheduler == "kueue" %}suspend: true{% endif %}
  # alpha in 1.30 so not supported yet
  # successPolicy:
  #  - succeededIndexes: "0"
  template:
    metadata:
      labels:
        app: {{ name }}
        {% if scheduler == "scheduler-plugins-scheduler" %}scheduling.x-k8s.io/pod-group: {{ name }}{% endif %}
        {% if scheduler == "kueue" %}kueue.x-k8s.io/queue-name: "user-queue"
#        kueue.x-k8s.io/pod-group-total-count: "{{ size }}"
#      annotations:
#        kueue.x-k8s.io/pod-group-name: "{{ name }}"{% endif %} 
    spec:
      subdomain: {{ service_name }}
{% if scheduler %}{% if scheduler != 'kueue' %}
      schedulerName: {{ scheduler }}{% endif %}{% endif %}
      restartPolicy: Never
      containers:
      - name: example-workload
        image: bash:latest
        resources:
          limits:
            cpu: "{{ cpu_limit }}"
          requests:
            cpu: "{{ cpu_limit }}"
        command:
        - bash
        - -c
        - |
          if [ $JOB_COMPLETION_INDEX -ne "0" ]
            then
              sleep infinity
          fi
          echo "START: $(date +%s%N | cut -b1-13)"
          for i in {{ size_range }}
          do
            gotStatus="-1"
            wantStatus="0"             
            while [ $gotStatus -ne $wantStatus ]
            do                                       
              ping -c 1 {{ name }}-${i}.{{ service_name }} > /dev/null 2>&1
              gotStatus=$?                
              if [ $gotStatus -ne $wantStatus ]; then
                echo "Failed to ping pod {{ name }}-${i}.{{ service_name }}, retrying in 1 second..."
                sleep 1
              fi
            done                                                         
            echo "Successfully pinged pod: {{ name }}-${i}.{{ service_name }}"
          done
          echo "DONE: $(date +%s%N | cut -b1-13)"
          # echo "DONE: $(date +%s)"

{% if scheduler == "scheduler-plugins-scheduler" %}---
# PodGroup CRD spec
apiVersion: scheduling.x-k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: {{ name }}
spec:
  scheduleTimeoutSeconds: 10
  minMember: {{ size }}
{% endif %}

