# matrix of experiments to run - machine types and sizes are required

# This can obviously be expanded to more sizes or machines,
matrix:
  size: [2]
  machine: ["n1-standard-1"]
  # machine: ["n1-standard-1", "n1-standard-2", "n1-standard-4", "n1-standard-8", "n1-standard-16", "n1-standard-32", "n1-standard-64"]

# Flux Mini Cluster experiment attributes
minicluster:
  name: osu-benchmarks
  namespace: flux-operator
  

# Each job can have a command and working directory
jobs:
  osu_get_latency:
    command: './osu_get_latency'
  osu_acc_latency:
    command: './osu_acc_latency'
  osu_fop_latency:
    command: './osu_fop_latency'
  osu_get_bw:
    command: './osu_get_bw'
  osu_put_bibw:
    command: './osu_put_bibw'
  osu_put_latency:
    command: './osu_put_latency'
  osu_cas_latency:
    command: './osu_cas_latency'
  osu_get_acc_latency:
    command: './osu_get_acc_latency'
  osu_put_bw:
    command: './osu_put_bw'