apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: scaling-study-efa
  region: us-east-1
  version: "1.27"

# TODO we need AL2_ARM_64
availabilityZones: ["us-east-1a", "us-east-1b"]
managedNodeGroups:
  - name: workers
    availabilityZones: ["us-east-1a"]
    instanceType: hpc7g.16xlarge
    # Defaults to 80, this in GB. 80 is too small to support installing EFA
    volumeSize: 150
    # This should only be needed if we had a list to choose from
    #instanceSelector:
    #  cpuArchitecture: arm64 
    minSize: 8
    maxSize: 8
    efaEnabled: true
    placement:
      groupName: eks-efa-testing
    labels: { "flux-operator": "true" }
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_eks.pub
