# matrix of experiments to run - machine types and sizes are required

# These are mini runs intended for testing
matrix:
  size: [4]
  machine: ["m5.large"]

# Flux Mini Cluster experiment attributes
minicluster:
  name: lammps
  namespace: flux-operator
  size: [2, 4]

jobs:
  lmp:
    command: lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite
    repeats: 3
    image: ghcr.io/rse-ops/lammps:flux-sched-focal-v0.24.0
    workdir: /home/flux/examples/reaxff/HNS